### ISSUE TITLE
Work Cited.

### ISSUE THREAD

**Issue by grabear** [datasnakes/Datasnakes-Scripts#21]
Go through different code and preform work cited where necessary in a md or rst document.
Comment code with Work Cited Index numbers.
Do research to see if there is a standard way to do works cited for programming projects.
```json
    Format:
{
file: 'file',
path: 'path',
line: 000,
citation: 'biopython',
etc: 'etc'
}
```

**Comment by sdhutchins** [comment]
I think this is just going to come down to adding in citations from the services/programs we used.

- [ ] Guidance2
- [ ] Pal2nal
- [ ] IQTree
- [ ] Clustal Omega
- [ ] Biopython
- [ ] ETE
- [ ] PhyML
- [ ] Treelib?
- [ ] BioSQl?

Feel free to add more or the rest.

**Comment by grabear** [comment]
> I think this is just going to come down to adding in citations from the services/programs we used.
> 
> - [ ] Guidance2
>   **When citing the GUIDANCE2 server please refer to:**
>   Sela, I., Ashkenazy, H., Katoh, K. and Pupko, T. (2015)
>   GUIDANCE2: accurate detection of unreliable alignment regions accounting for the uncertainty of 
>   multiple parameters.
>   Nucleic Acids Research, 2015 Jul 1; 43 (Web Server issue): W7-W14.; doi: 10.1093/nar/gkq443 
> 
>   Landan, G., and D. Graur. (2008).
>   Local reliability measures from sets of co-optimal multiple sequence alignments.
>   Pac Symp Biocomput 13:15-24 [ABS] [PDF] 
> 
>   Penn, O., Privman, E., Ashkenazy, H., Landan, G., Graur, D. and Pupko, T. (2010).
>   GUIDANCE: a web server for assessing alignment confidence scores.
>   Nucleic Acids Research, 2010 Jul 1; 38 (Web Server issue):W23-W28; doi: 10.1093/nar/gkq443
> 
>     **When using the GUIDANCE2 algorithm please cite:**
>     Sela, I., Ashkenazy, H., Katoh, K. and Pupko, T. (2015)
>     GUIDANCE2: accurate detection of unreliable alignment regions accounting for the uncertainty of 
>     multiple parameters.
>     Nucleic Acids Research, 2015 Jul 1; 43 (Web Server issue): W7-W14.; doi: 10.1093/nar/gkq443 
> 
>     Landan, G., and D. Graur. (2008).
>     Local reliability measures from sets of co-optimal multiple sequence alignments.
>     Pac Symp Biocomput 13:15-24 [ABS] [PDF] 
> 
> 
>     **When using the GUIDANCE algorithm please cite:**
>     Penn, O., Privman, E., Landan, G., Graur, D. and Pupko, T. (2010).
>     An alignment confidence score capturing robustness to guide-tree uncertainty. 
>     Molecular Biology and Evolution, 2010 Aug;27(8):1759-67; doi:10.1093/molbev/msq066 [ABS] [PDF] 
> 
> 
>   **When using the HoT algorithm please cite:**
>   Landan, G., and D. Graur. (2008).
>   Local reliability measures from sets of co-optimal multiple sequence alignments.
>   Pac Symp Biocomput 13:15-24 [ABS] [PDF]
> 
> - [ ] Pal2nal
> **If you use PAL2NAL, please cite the following paper:**
> Mikita Suyama, David Torrents, and Peer Bork (2006)
> PAL2NAL: robust conversion of protein sequence alignments into the corresponding codon alignments.
> Nucleic Acids Res. 34, W609-W612.
> - [ ] IQTree
> **This One is a bit more complicated.**
> - [ ] Clustal Omega
>   **Citing Clustal**
> Sievers F, Wilm A, Dineen DG, Gibson TJ, Karplus K, Li W, Lopez R, McWilliam H, Remmert M, Söding J, > Thompson JD, Higgins DG (2011). Fast, scalable generation of high-quality protein multiple sequence > alignments using Clustal Omega. Molecular Systems Biology 7:539 doi:10.1038/msb.2011.75
> - [x] Biopython
> - [ ] ETE
> - [ ] PhyML
> - [ ] Treelib?
> - [ ] BioSQl?
> 
> Feel free to add more or the rest.

**Comment by grabear** [comment]
Stealing this. https://github.com/etetoolkit/ete/blob/master/ete3/citation.py

**Comment by grabear** [comment]
### New way of adding references:
A new class has been designed to hold all of our info.  Right now it's called "Webster".
In the future we can add static YAML files to Manager/config/webster that will hold data that we regularly call.  This will be particularly useful when using the YAML tagging for python objects and modules (#118).  This will give us better readability as well as a better way to implement function dispatching.
```yaml
GUIDANCE2:
  reference_1:
    citation: "Sela, I., Ashkenazy, H., Katoh, K. and Pupko, T. (2015) GUIDANCE2: Accurate Detection of
    Unreliable Alignment Regions Accounting for the Uncertainty of Multiple Parameters.  Nucleic Acids
    Research, 2015 Jul 1; 43 (Web Server issue): W7-W14.; doi: 10.1093/nar/gkq443"
    link: "https://www.ncbi.nlm.nih.gov/pubmed/18229673"
    path: '!!python/object/apply:pkg_resources.resource_filename [Datasnakes.Manager.config.references, "GUIDANCE2_Accurate_Detection_of_Unreliable_Alignment_Regions_Accounting_for_the_Uncertainty_of_Multiple_Parameters.pdf"]'
  reference_2:
    citation: "Landan, G., and D. Graur. (2008).  Local Reliability Measures from Sets of Co-optimal
    Multiple Sequence Alignments.  Pac Symp Biocomput 13:15-24"
    link: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4489236/"
    path: '!!python/object/apply:pkg_resources.resource_filename [Datasnakes.Manager.config.references, "Local_Reliability_Measures_from_Sets_of_Co-optimal_Multiple_Sequence_Alignments.pdf"]'
PAL2NAL:
  reference_1:
    citation: "Mikita Suyama, David Torrents, and Peer Bork (2006) PAL2NAL: Robust Conversion of Protein
    Sequence Alignments Into the Corresponding Codon Alignments.  Nucleic Acids Res. 34, W609-W612."
    link: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1538804/"
    path: '!!python/object/apply:pkg_resources.resource_filename [Datasnakes.Manager.config.references, "PAL2NAL_ Robust_Conversion_of_Protein_Sequence_Alignments_into_the_Corresponding_Codon_Alignments.pdf]'
IQTREE:
  reference_1:
    citation: "LT Nguyen, H.A. Schmidt, A. von Haeseler, and BQ Minh (2015) IQ-TREE: A
    fast and effective stochastic algorithm for estimating maximum likelihood
    phylogenies. Mol. Biol. Evol., 32, 268-274."
    link: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4271533/"
    path: '!!python/object/apply:pkg_resources.resource_filename [Datasnakes.Manager.config.references, "IQ-TREE_A_Fast_and_Effective_Stochastic_Algorithm_for_Estimating_Maximum-Likelihood_Phylogenies.pdf"]'
CLUSTALO:
  reference_1:
    citation: "Sievers F, Wilm A, Dineen D, Gibson TJ, Karplus K, Li W, Lopez R, McWilliam H, Remmert M,
    Söding J, Thompson JD, Higgins DG.  Fast, Scalable Generation of High-quality Protein Multiple Sequence
    Alignments Using Clustal Omega.  Mol Syst Biol. 2011 Oct 11;7:539. doi: 10.1038/msb.2011.75."
    link: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3261699/"
    path: '!!python/object/apply:pkg_resources.resource_filename [Datasnakes.Manager.config.references, "Datasnakes/Manager/config/references/Fast_Scalable_Generation_of_High-Quality_Protein_Multiple_Sequence_Alignments_Using_Clustal_Omega.pdf"]'
```
