### ISSUE TITLE
Update Alignment configuration.

### ISSUE THREAD

**Issue by grabear** [datasnakes/Datasnakes-Scripts#93]
While the other modules are configuring successfully [now](), the data management class's configuration for the alignment class needs to change.  Since each alignment takes different parameters, Each type of alignment will have it's own nested key-value pairs in the Alignment_config variable that exists in the YAML files.  Guidance for example will look like this:
```yaml
Alignment_config:
  aln_program: 'GUIDANCE2'
  Guidance_config:
    seqFile: "~\\Datasnakes-Scripts\\Datasnakes\\Manager\\config\\test.faa"
    msaProgram: "CLUSTALW"
    seqType: "nuc"
```
Further down the road we can do this for a consensus alignment:
```yaml
Alignment_config:
  aln_program: 'GUIDANCE2'
  Consensus_config:
    Guidance_config:
      seqFile: "~\\Datasnakes-Scripts\\Datasnakes\\Manager\\config\\test.faa"
      msaProgram: "CLUSTALW"
      seqType: "nuc"
    IQ-Tree_config:
      var1:  "hope"
      var2: "dreams"
```
Obviously there are other options, but for now we've got to _KISS_.

**Comment by grabear** [comment]
Helped fixed with function dispatching in commit 9d6bd5068ec66fcdff28c0e873859c3a9e9a2824.

Function dispatching looks like this:

```python
self.config_options = {"Guidance_config": ["GUIDANCE2", self.guidance2], "Pal2Nal_config": ["PAL2NAL", self.pal2nal], "ClustalO_config": ["CLUSTALO", self.clustalo]}
```

Where you use a function in a dictionary without making an actual call to it.  This helps with identifying what function to use based on the config options set in the YAML config file:
```yaml
Alignment_config:
  aln_program: 'GUIDANCE2'
  Guidance_config:
    seqFile: "~\\Datasnakes-Scripts\\Datasnakes\\Manager\\config\\test.faa"
    msaProgram: "CLUSTALW"
    seqType: "nuc"  
```
