### ISSUE TITLE
Database Management for the pipeline.

### ISSUE THREAD

**Issue by grabear** [datasnakes/Datasnakes-Scripts#95]
- Database Management will first be developed in Manager/database_management.py
- It will help keep the following databases updated:
    - [ ] ETE3's NCBI-taxonomy database
      - [ ] Use new_basic_project cookiecutter hook
    - [ ] GenBank files from NCBI's Refseq database (BioSQL)
      - [ ] Proprietary GenBank databases (BioSQL)
    - [ ] Local NCBI BLAST database
      - [ ] gi lists
        * vertebrate_mammalian
        * bacterial

**Comment by sdhutchins** [comment]
@grabear status? Closeable? lol

**Comment by grabear** [comment]
Not yet lol. @sdhutchins

**Comment by grabear** [comment]
Update on this issue.
# Scope
* Manager/BioSQL/biosql.py
* Manager/database_management.py
* Manager/database_dispatcher.py
* Manager/utils.py
* Manager/config/yml/database_config.yml
* Manager/db_mana_test.py

# Tested Functionality
_The following checked items have been tested by changing the parameters in the config file._
- [ ] Logging is looking amazing.
- [ ] YAML config file format (**database_config.yml**)


## Configuration

- [ ] Dispatching database management tasks (**database_dispatcher.py** via **database_management.py**)
    - [ ] BioSQL creation (**biosql.py**)
        - [ ] SQLite
            - [ ] BioSQL template creation with schema and NCBI taxonomy
        - [ ] MySQL
            - [ ] BioSQL template creation with schema and NCBI taxonomy
    - [ ] NCBI tasks
        - [ ] blast downloading
            - [ ] db downloading
            - [ ] windowmasker files downloading
        - [ ] pub taxonomy downloading
        - [ ] refseq release
            - [ ] downloading
            - [ ] uploading to BioSQL
    - [ ] ITIS downloads
- [ ] Configuration on a per project basis

## Archiving
_Bugs need to be fixed with the file movement and deletion after archiving._
- [ ] Archiving

## Deletion
_Not Tested_

# Config File Explanation and Preview
The config file is loaded into Python as a nested dictionary.  The top key value pairs such as:
```yaml
email:  "rgilmore@umc.edu"
driver: "sqlite3"
```
are used for changing the parameters in the _BaseDatabaseManagement_ class.

The various strategies for dispatching tasks include the following and are dictionary keys:
```python
['Full', 'Projects', 'NCBI', 'NCBI_blast', 'NCBI_blast_db', 'NCBI_blast_windowmasker_files', 'NCBI_pub_taxonomy', 'NCBI_refseq_release', 'ITIS', 'ITIS_taxonomy']
```
Some keys are nested in the config file.  The concept to note here is that top level keys (or strategies) have flags that control any sub level strategies.  So if the _configure_flag_ for 'Full' is _True_, then the _configure_flag_ for 'Projects', 'NCBI', 'NCBI_blast', 'NCBI_blast_db', 'NCBI_blast_windowmasker_files', 'NCBI_pub_taxonomy', 'NCBI_refseq_release', 'ITIS', and 'ITIS_taxonomy' will also be interpreted as _True_ when the database functions are dispatched.

Below I've added a preview of the entire database_config.yml file for consideration of the above statements.

```yaml
Database_config:
  email:  "rgilmore@umc.edu"
  driver: "sqlite3"
  Full:
    configure_flag: False
    archive_flag: False
    delete_flag: False
    project_flag: False
    _path: "!!python/object/apply:pathlib.Path ['']"
    Projects:
      Project_Name_1:
        configure_flag: True
        archive_flag: False
        delete_flag: False
        _path: "!!python/object/apply:pathlib.Path ['Project_Name_1']"
      Project_Name_2:
        configure_flag: True
        archive_flag: False
        delete_flag: False
        _path: "!!python/object/apply:pathlib.Path ['Project_Name_2']"
      Project_Name_3:
        configure_flag: True
        archive_flag: False
        delete_flag: False
        _path: "!!python/object/apply:pathlib.Path ['Project_Name_3']"
    NCBI:
      configure_flag: False
      archive_flag: False
      delete_flag: False
      _path: "!!python/object/apply:pathlib.Path ['NCBI']"
      NCBI_blast:
        configure_flag: False
        archive_flag: False
        delete_flag: False
        _path: "!!python/object/apply:pathlib.Path ['NCBI', 'blast']"
        NCBI_blast_db:
          configure_flag: False
          archive_flag:  False
          delete_flag: False
          _path: "!!python/object/apply:pathlib.Path ['NCBI', 'blast', 'db']"
        NCBI_blast_windowmasker_files:
          configure_flag: False
          archive_flag: False
          delete_flag: False
          _path: "!!python/object/apply:pathlib.Path ['NCBI', 'blast', 'windowmasker_files']"
          taxonomy_ids: ""
      NCBI_pub_taxonomy:
        configure_flag: True
        archive_flag: False
        delete_flag: False
        _path: "!!python/object/apply:pathlib.Path ['NCBI', 'pub', taxonomy']"
      NCBI_refseq_release:
        seqtype: "rna" # Other seqtypes are protein and genomic
        seqformat: "gbff"
        collection_subset: "vertebrate_mammalian"
        configure_flag: False
        archive_flag: False
        delete_flag: False
        upload_flag: False
        _path: "!!python/object/apply:pathlib.Path ['NCBI', 'refseq', 'release']"
        upload_list: [1,2,3,4,5,6,7,8,9,10]
    ITIS:
      configure_flag: True
      archive_flag: False
      delete_flag: False
      _path: "!!python/object/apply:pathlib.Path ['ITIS']"
      ITIS_taxonomy:
        configure_flag: True
        archive_flag: False
        delete_flag: False
        _path: "!!python/object/apply:pathlib.Path ['ITIS', 'taxonomy']"
```
